CREATE TABLE PATRON (
patron_id   NUMBER GENERATED by default on null as IDENTITY,
first_name  VARCHAR2(50) NOT NULL,
last_name   VARCHAR2(50) NOT NULL,
areacode    VARCHAR2(255),
phone       VARCHAR2(255),
street      VARCHAR2(100),
city        VARCHAR2(100),
state       VARCHAR2(2),
zip         VARCHAR2(11),

CONSTRAINT patron_pk PRIMARY KEY (patron_id)
);

CREATE TABLE BRANCH (
branch_id 	NUMBER GENERATED by default on null as IDENTITY,
branch_name 	VARCHAR2(255) NOT NULL,	
branch_areacode VARCHAR2(255),
branch_phone 	VARCHAR2(255),
CONSTRAINT branch_pk PRIMARY KEY (branch_id)
);

CREATE TABLE BOOK (
book_id 	    NUMBER GENERATED by default on null as IDENTITY,
branch_id 		NUMBER(2) NOT NULL,
book_name 		VARCHAR2(255) NOT NULL,
book_ISBN 		VARCHAR2(13) NOT NULL,
book_author_fname 	VARCHAR2(50),
book_author_lname 	VARCHAR2(50),
CONSTRAINT book_pk PRIMARY KEY (book_id),
CONSTRAINT fk_BOOK_BRANCH
  FOREIGN KEY (branch_id)
  REFERENCES BRANCH (branch_id)
);

CREATE TABLE CHECKOUT (
checkout_id 	NUMBER GENERATED by default on null as IDENTITY,
patron_id 	NUMBER(8),
book_id 	NUMBER(10), 
checkout_date 	DATE,
due_date 	DATE,
returned_date   DATE,
CONSTRAINT checkout_pk PRIMARY KEY (checkout_id),
CONSTRAINT fk_CHECKOUT_PATRON
 FOREIGN KEY (patron_id)
 REFERENCES PATRON (patron_id),
CONSTRAINT fk_CHECKOUT_BOOK
 FOREIGN KEY (book_id)
 REFERENCES BOOK (book_id)
);


CREATE OR REPLACE PROCEDURE Retrieve_Overdue_Books_From_Sunnydale(VAR OUT SYS_REFCURSOR)
AS

BEGIN
    OPEN VAR FOR
    SELECT first_name, last_name, checkout_date, due_date, areacode, phone
    FROM CHECKOUT JOIN PATRON ON CHECKOUT.patron_id = PATRON.patron_id
                  JOIN BOOK ON CHECKOUT.book_id = BOOK.book_id
    WHERE returned_date IS NULL 
    AND DUE_DATE < SYSDATE;
END;
